spring.application.name=PlacementHub
server.port=8080

# Profile
spring.profiles.active=dev

# File Upload
file.upload-dir=uploads/resumes
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
# Frontend URL
app.frontend-url=${FRONTEND_URL:http://localhost:5173}
# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration-milliseconds=${JWT_EXPIRATION:604800000}